#!/bin/sh

# zabbix-voip-http-push
# Copyright (C) 2023, 2024  Prefeitura Municipal de Campo Largo <analistas@campolargo.pr.gov.br>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

. .venv/bin/activate
if [ "$1" = "debug" ]; then
    gunicorn -w 4 app:app --access-logfile=-
else
    gunicorn -w 4 app:app --access-logfile=app.log -D
fi
deactivate
